app/models/house.rb
app/models/user.rb
db/migrate/20230824140956_create_houses.rb
db/migrate/20230826031839_add_add_user_ref_to_houses.rb
db/schema.rb
db/seeds.rb
test/models/house_test.rb

1) Created model house
2) Migrated 
3) Created 1 data point in the seed file and please review on saturday!

Added model house and seeded 1 house

---

app/models/house.rb
app/models/offer.rb
app/models/user.rb
db/migrate/20230826040510_create_offers.rb
db/schema.rb
test/models/offer_test.rb

done with creating model-offers and its respective migration tables. kindly review!

created model-offers and migration updates

---

app/controllers/houses_controller.rb
app/views/houses/_form.html.erb
app/views/houses/_listing.html.erb
app/views/houses/edit.html.erb
app/views/houses/index.html.erb
app/views/houses/new.html.erb
app/views/houses/show.html.erb
app/views/pages/home.html.erb
config/routes.rb
test/controllers/houses_controller_test.rb

Please check if the houses and routes are working for you and then we will start to do authorization

added CRUD and routes for houses

---

Gemfile
Gemfile.lock
app/models/house.rb
db/seeds.rb

Created seed file and validation for the house model, please review!

Seed data generation

---

app/models/house.rb
app/models/user.rb

added dependent destroy on user(house and offers dependent on user) and house(offers dependent on house) models, please review!

added dependent destroy on user and house models

---

app/controllers/houses_controller.rb
app/models/house.rb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb
app/views/houses/_form.html.erb

Completed listing form for 3 changes:
1. categorization for tenure & house
2. Bed room and bathroom dropdown
3. redirection to crrated house

Listing form sean

---

app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb

1. added containers for all signup/sign in forms and forgot passwords.
2. changed 'login' to 'already a user? log in"

Signup page

---

app/controllers/application_controller.rb
app/controllers/houses_controller.rb
app/views/houses/my_listings.html.erb
app/views/houses/my_offers.html.erb
app/views/pages/_featured.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

Create my offer page
- if the user has submitted and offer it will show the list of houses that he/she submitted the offer
- if there is no offer submitted it will show no offer

My offer page

---

app/views/houses/_listing.html.erb
app/views/houses/index.html.erb
app/views/houses/my_listings.html.erb
app/views/houses/show.html.erb
db/seeds.rb

Summary of changes:
- added details to card listings in index
- added photos to seed houses
Index:
- added searchbar
- added price per square foot calculation
- beautified the card to include more details and minimum ask price. 
Show:
- added photo

added features to our index and added images to seed

---

.gitignore
app/controllers/houses_controller.rb
app/controllers/offers_controller.rb
app/models/house.rb
app/models/offer.rb
app/views/favourites/index.html.erb
app/views/houses/_listing.html.erb
app/views/houses/my_listings.html.erb
app/views/houses/my_offers.html.erb
app/views/houses/show.html.erb
app/views/pages/_featured.html.erb
app/views/shared/_navbar.html.erb
db/seeds.rb

1) Added YY code to validate the price with the error message  and temp fix the layout on how to display the submit offer form so that the error can be shown
2) fix the logic for My-offers page as it was generating new cards for the same house if the user were to place a 2nd offer.
3) synchronize all labels
4) added dependent destroy to the house model for favourites

Offer validation

---

app/views/houses/show.html.erb

Feature update
Added bootstrap class="sticky-top' so that offer form is sticky 
Noted current UI will not see it being sticky as all information is viewable without scroll.
If needed to be tested duplicate the information section so that it scrolls and you will see the form sticky

feature/added sticky-top class to offer form

---

app/views/houses/_listing.html.erb

Feature update
Added Highest Offered Price to Index Cards

feature/ add highest offered price to index card

---

app/assets/stylesheets/components/_favourites.scss
app/assets/stylesheets/components/_index.scss
app/controllers/houses_controller.rb
app/javascript/controllers/favouritesbtn_controller.js
app/javascript/controllers/index.js
app/views/houses/show.html.erb

Added Favourites button changes and pop up message. had difficulty using the same flash[:notice] popup that comes up from signing in signing out. 
So instead added a pop up message that disappears in 1.5s. pls see screenshots for reference.
1. pre-adding
2. post-click add to fav
3. pop up message disappears after 1.5s
same for reverse

Favourites icon

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_scroll.css.scss
app/controllers/houses_controller.rb
app/javascript/controllers/address_autocomplete_controller.js
app/javascript/controllers/index.js
app/javascript/controllers/scroll_controller.js
app/models/house.rb
app/views/houses/_form.html.erb
app/views/houses/_info_window.html.erb
app/views/houses/_listing.html.erb
app/views/houses/show.html.erb
db/migrate/20230902055356_add_region_to_houses.rb
db/schema.rb
db/seeds.rb

Completed changes:
- updated house model to incorporate Region
- Added Region (which is autofilled when address autocomplete via the Mapbox) to form
source: https://www.iso.org/obp/ui/#iso:code:3166:SG possible regions
- added this to Show cards at the top --> this will be used for search later
- added to seed files region
- added scroll feature to the map on the index page (see Slack for this preview)
Work in progress
- expanding database seed file

Geocoder region

---

app/controllers/houses_controller.rb
app/views/houses/show.html.erb

Removed authentication requirements from show and index pages from home page

removed authentication from show page and index

---

app/controllers/offers_controller.rb
app/policies/house_policy.rb
app/policies/offer_policy.rb
app/views/houses/my_listings.html.erb
app/views/houses/show.html.erb
config/routes.rb

done up the buttons for offers:
1. delete and edit buttons are up
2. the constraints logic should also b working fine, in terms of having accepted offer, or if the user already submitted 1 offer. 
3. need to fix validation logic for update overlay button. (TBD)

Listing button changes

---

Gemfile
Gemfile.lock
app/controllers/houses_controller.rb
app/models/house.rb
app/views/pages/_search.html.erb

pls use this for search functionality push instead of the previous search pull request.
Filters not up.

final push for search

---

app/assets/stylesheets/components/_buttons.scss
app/assets/stylesheets/components/_index.scss
app/controllers/offers_controller.rb
app/javascript/controllers/accept_offers_controller.js
app/javascript/controllers/index.js
app/models/offer.rb
app/policies/house_policy.rb
app/policies/offer_policy.rb
app/views/houses/show.html.erb
app/views/layouts/application.html.erb
config/routes.rb
db/migrate/20230905034836_change_status_default_in_offers_to_pending.rb
db/schema.rb

still encountering bugs - for guidance (ZH)

created buttons but still encountering bugs

---

app/assets/stylesheets/components/_favourites.scss
app/javascript/controllers/favouritesbtn_controller.js
db/schema.rb

Favourites pop up message edited to be similar to the sign in message.

pop up message favourites added

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search_bar.scss
app/controllers/houses_controller.rb
app/views/houses/index.html.erb
app/views/houses/show.html.erb
app/views/pages/_featured.html.erb
app/views/pages/_search.html.erb
app/views/pages/home.html.erb

@jacobkhong over to u for front end... u can pull this and backend should work.

backend for filters + rushed form for filters done

---

app/views/favourites/index.html.erb
app/views/houses/my_listings.html.erb
app/views/houses/my_offers.html.erb

Fix back icon to add :back (from YY code)

fix back icon to :back path

---

app/views/houses/show.html.erb

fixed edit button submit button clicking

edit button fixed
